-- OSM data © OpenStreetMap contributors, ODbL 1.0. Review before executing.
-- Requires 20261007130000_real_map_catalog.sql. Does not remove vanished businesses.
begin;
set local standard_conforming_strings = on;
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-11195408737', 'Laudry express', 20, NULL, '', 'Beirut', '', '', '', 33.8761067, 35.4912567, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/11195408737","names":["Laudry express"],"updatedAt":"2023-09-16T08:06:28Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":""}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-12638855101', 'النجار جهاد عرابي', 11, NULL, '', 'Beirut', 'شارع المرج', '+96170914978', '', 33.8769671, 35.494335, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/12638855101","names":["النجار جهاد عرابي"],"updatedAt":"2025-03-05T21:24:37Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":"Mo-Sa 08:00-16:30"}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-13376250701', 'A Plus Dry Clean Laundry Service', 20, NULL, '', 'Beirut', 'شارع أمين منيمنة', '+96170770577', '', 33.8923805, 35.4853556, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/13376250701","names":["A Plus Dry Clean Laundry Service"],"updatedAt":"2026-02-07T22:31:26Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":""}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-3314071786', 'Terra Cool', 9, NULL, '', 'Beirut', '', '+9611580300', '', 33.8931404, 35.5333746, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/3314071786","names":["Terra Cool"],"updatedAt":"2020-10-20T17:53:53Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":""}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-4165121193', 'Immediate Service', 20, NULL, '', 'Beirut', 'شارع الشيخ الياس كسبار', '+96171719530', '', 33.8966668, 35.4794505, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/4165121193","names":["Immediate Service","Service immédiat"],"updatedAt":"2023-07-03T11:18:38Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":"Mo-Sa 08:00-19:00"}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-4247951396', 'دي آش إل', 18, NULL, '', 'Beirut', 'شارع الأمير بشير', '+9611629700', '', 33.8946945, 35.5057092, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/4247951396","names":["دي آش إل","DHL"],"updatedAt":"2023-04-18T11:31:39Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":"Mo-Fr 09:00-22:00"}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-4252709605', 'Nazo', 3, NULL, '', 'Beirut', 'كورنيش بيار الجميل', '', '', 33.8947579, 35.5350269, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/4252709605","names":["Nazo"],"updatedAt":"2017-06-17T07:30:21Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":""}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-4401529489', 'ناتكو (كيا)', 3, NULL, '', 'Beirut', '', '+9611574999', '', 33.8889766, 35.5322841, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/4401529489","names":["ناتكو (كيا)","Natco (Kia)"],"updatedAt":"2022-01-30T17:09:21Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":"Mo-Fr 07:30-16:30"}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-4543035249', 'مصبغة بلازا', 20, NULL, '', 'Beirut', 'شارع بني معروف', '+9611740260', '', 33.8902191, 35.4869465, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/4543035249","names":["مصبغة بلازا","Plaza Laundry","Laverie Plaza"],"updatedAt":"2023-07-03T11:22:42Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":"Mo-Fr 07:30-19:00; Sa 07:30-16:00"}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-4943782962', 'Elegance Cleaners', 20, NULL, '', 'Beirut', '', '', '', 33.8882701, 35.5250821, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/4943782962","names":["Elegance Cleaners"],"updatedAt":"2018-03-04T11:43:50Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":""}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-5046303893', 'Bashir Services', 19, NULL, '', 'Beirut', 'شارع ألفرد نوبل', '+96176608658', '', 33.8930025, 35.4835614, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/5046303893","names":["Bashir Services"],"updatedAt":"2023-06-18T16:12:40Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":"Mo-Su 10:00-20:00"}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-5073699722', 'كراج الحمرا', 3, NULL, '', 'Beirut', '', '', '', 33.8940746, 35.4834079, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/5073699722","names":["كراج الحمرا"],"updatedAt":"2017-10-09T19:59:10Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":""}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-6038757496', 'La Perlla', 20, NULL, '', 'Beirut', '', '', '', 33.9003052, 35.489425, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/6038757496","names":["La Perlla"],"updatedAt":"2018-11-05T08:53:51Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":""}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-6308702404', 'أبكو', 9, NULL, '', 'Beirut', '', '', '', 33.8967473, 35.5252054, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/6308702404","names":["أبكو","ABCO"],"updatedAt":"2019-02-28T17:51:24Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":""}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-6418357585', 'Laundry Gemayze', 20, NULL, '', 'Beirut', '', '', '', 33.8955314, 35.5118698, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/6418357585","names":["Laundry Gemayze"],"updatedAt":"2019-04-20T18:52:59Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":""}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-node-7934745687', 'Alexander Dry Clean', 20, NULL, '', 'Beirut', 'Adiba Ishac', '', '', 33.8836566, 35.5189817, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/node/7934745687","names":["Alexander Dry Clean"],"updatedAt":"2021-07-25T19:57:21Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":""}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-way-263183380', 'FOLIC AUTOMOTIVE S.A.L.', 3, NULL, '', 'Beirut', 'Ramlet El Baydah 3646 bldg., Msaytbeh', '', '', 33.874919, 35.4867343, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/way/263183380","names":["FOLIC AUTOMOTIVE S.A.L.","Ford / Land Rover Service"],"updatedAt":"2023-01-04T20:05:47Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":""}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-way-514515333', 'أبلو', 3, NULL, '', 'Beirut', '', '', '', 33.8761404, 35.5195032, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/way/514515333","names":["أبلو","Apollo"],"updatedAt":"2022-12-16T02:43:17Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":""}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-way-587658794', 'Mitsubishi', 3, NULL, '', 'Beirut', '', '', '', 33.8816394, 35.5302721, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/way/587658794","names":["Mitsubishi"],"updatedAt":"2021-09-22T07:36:52Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":""}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
insert into public.providers (id, name, category_id, owner_id, description, area, address, phone, whatsapp, latitude, longitude, opening_hours, is_verified, listing_status, service_mode, price_type, starting_price, emergency_service, price_currency, years_experience, moderation_status, moderation_reason, moderated_at, map_source) values ('osm-way-795349271', 'Zakariya', 11, NULL, '', 'Beirut', '', '', '', 33.8865161, 35.5035438, '{}', false, 'published', 'on_site', 'quote', NULL, false, 'USD', NULL, 'active', '', NULL, '{"kind":"openstreetmap","url":"https://www.openstreetmap.org/way/795349271","names":["Zakariya"],"updatedAt":"2020-04-23T17:22:26Z","importedAt":"2026-10-08T10:28:38.854Z","openingHours":""}')
on conflict (id) do update set name = excluded.name, category_id = excluded.category_id, description = excluded.description, area = excluded.area, address = excluded.address, phone = excluded.phone, whatsapp = excluded.whatsapp, latitude = excluded.latitude, longitude = excluded.longitude, opening_hours = excluded.opening_hours, service_mode = excluded.service_mode, price_type = excluded.price_type, starting_price = excluded.starting_price, emergency_service = excluded.emergency_service, price_currency = excluded.price_currency, years_experience = excluded.years_experience, map_source = excluded.map_source
where providers.owner_id is null and providers.map_source->>'kind' = 'openstreetmap'
  and providers.listing_status = 'published' and providers.moderation_status = 'active';
commit;
