// Local MVP data. These records are intentionally shaped like the future
// database rows, so the UI can move to Supabase without being redesigned.

import { Category, Provider, Review } from './types';

export const CATEGORIES: Category[] = [
  { id: 1, name: 'Plumbers', nameAr: 'سباكون', icon: 'water-outline' },
  { id: 2, name: 'Electricians', nameAr: 'كهربائيون', icon: 'flash-outline' },
  { id: 3, name: 'Mechanics', nameAr: 'ميكانيكيون', icon: 'car-sport-outline' },
  { id: 4, name: 'Roadside Tire Help', nameAr: 'مساعدة إطارات', icon: 'disc-outline' },
  { id: 5, name: 'Car Battery Help', nameAr: 'بطاريات سيارات', icon: 'battery-charging-outline' },
  { id: 6, name: 'Towing', nameAr: 'سحب سيارات', icon: 'car-outline' },
  { id: 7, name: 'Cleaning Services', nameAr: 'خدمات تنظيف', icon: 'sparkles-outline' },
  { id: 8, name: 'House Maintenance', nameAr: 'صيانة منزلية', icon: 'home-outline' },
  { id: 9, name: 'AC Repair', nameAr: 'تصليح مكيفات', icon: 'snow-outline' },
  { id: 10, name: 'Appliance Repair', nameAr: 'تصليح أجهزة', icon: 'build-outline' },
  { id: 11, name: 'Carpenters', nameAr: 'نجارون', icon: 'hammer-outline' },
  { id: 12, name: 'Painters', nameAr: 'دهانون', icon: 'color-palette-outline' },
  { id: 13, name: 'Locksmiths', nameAr: 'صانعو أقفال', icon: 'key-outline' },
  { id: 14, name: 'Pest Control', nameAr: 'مكافحة حشرات', icon: 'bug-outline' },
  { id: 15, name: 'Moving Services', nameAr: 'خدمات نقل', icon: 'cube-outline' },
  { id: 16, name: 'Mobile Car Wash', nameAr: 'غسيل سيارات متنقل', icon: 'car-outline' },
  { id: 17, name: 'Handyman', nameAr: 'عامل صيانة', icon: 'construct-outline' },
  { id: 18, name: 'Delivery & Errands', nameAr: 'توصيل ومشاوير', icon: 'bicycle-outline' },
  { id: 19, name: 'Phone/Laptop Repair', nameAr: 'تصليح هواتف وكمبيوتر', icon: 'phone-portrait-outline' },
  { id: 20, name: 'Laundry Services', nameAr: 'خدمات غسيل', icon: 'shirt-outline' },
];

const STANDARD_HOURS = {
  mon: '8:00–18:00',
  tue: '8:00–18:00',
  wed: '8:00–18:00',
  thu: '8:00–18:00',
  fri: '8:00–18:00',
  sat: '8:00–16:00',
  sun: 'Closed',
};

const ALWAYS_OPEN = {
  mon: '24 hours',
  tue: '24 hours',
  wed: '24 hours',
  thu: '24 hours',
  fri: '24 hours',
  sat: '24 hours',
  sun: '24 hours',
};

export const PROVIDERS: Provider[] = [
  {
    id: 'p1',
    name: 'RapidFlow Plumbing',
    categoryId: 1,
    description: 'Emergency leak repairs, blocked drains, water tanks, and bathroom plumbing with same-day visits.',
    address: 'Hamra Street, near Commodore',
    area: 'Hamra',
    phone: '+9611341100',
    whatsapp: '9613110101',
    latitude: 33.8959,
    longitude: 35.4821,
    openingHours: { ...STANDARD_HOURS, sun: 'Emergency calls' },
    avgRating: 4.9,
    reviewCount: 128,
  },
  {
    id: 'p2',
    name: 'Beirut Electric Rescue',
    categoryId: 2,
    description: 'Fast electrical fault finding, breaker repairs, rewiring, and inverter or generator connections.',
    address: 'Mar Elias main road',
    area: 'Mar Elias',
    phone: '+9611702121',
    whatsapp: '9613110102',
    latitude: 33.8825,
    longitude: 35.4932,
    openingHours: ALWAYS_OPEN,
    avgRating: 4.8,
    reviewCount: 94,
  },
  {
    id: 'p3',
    name: 'Garage 961',
    categoryId: 3,
    description: 'Diagnostics, engine repairs, brakes, oil changes, and pre-purchase inspections for most car brands.',
    address: 'Quarantina industrial area',
    area: 'Quarantina',
    phone: '+9611580303',
    whatsapp: '9613110103',
    latitude: 33.9012,
    longitude: 35.5423,
    openingHours: STANDARD_HOURS,
    avgRating: 4.7,
    reviewCount: 83,
  },
  {
    id: 'p4',
    name: 'RoadReady Tire Help',
    categoryId: 4,
    description: 'Mobile flat-tire changes, puncture repair, tire inflation, and emergency roadside support.',
    address: 'Mobile service across Greater Beirut',
    area: 'Greater Beirut',
    phone: '+9613992404',
    whatsapp: '9613110104',
    latitude: 33.8886,
    longitude: 35.4955,
    openingHours: ALWAYS_OPEN,
    avgRating: 4.9,
    reviewCount: 176,
  },
  {
    id: 'p5',
    name: 'JumpStart Beirut',
    categoryId: 5,
    description: 'On-site jump starts, battery testing, and replacement battery delivery wherever your car is parked.',
    address: 'Mobile service across Beirut',
    area: 'Beirut',
    phone: '+9613992505',
    whatsapp: '9613110105',
    latitude: 33.8938,
    longitude: 35.5018,
    openingHours: ALWAYS_OPEN,
    avgRating: 4.8,
    reviewCount: 142,
  },
  {
    id: 'p6',
    name: 'SafeTow Lebanon',
    categoryId: 6,
    description: '24/7 towing for breakdowns and accidents, with clear arrival times and careful vehicle handling.',
    address: 'Operating from Dora highway',
    area: 'Dora',
    phone: '+9613992606',
    whatsapp: '9613110106',
    latitude: 33.907,
    longitude: 35.566,
    openingHours: ALWAYS_OPEN,
    avgRating: 4.7,
    reviewCount: 119,
  },
  {
    id: 'p7',
    name: 'NeatNest Cleaning',
    categoryId: 7,
    description: 'Home and office cleaning, deep cleans, move-in cleaning, and flexible weekly appointments.',
    address: 'Sassine Square',
    area: 'Achrafieh',
    phone: '+9611202707',
    whatsapp: '9613110107',
    latitude: 33.8885,
    longitude: 35.5205,
    openingHours: STANDARD_HOURS,
    avgRating: 4.8,
    reviewCount: 101,
  },
  {
    id: 'p8',
    name: 'HomeCare Beirut',
    categoryId: 8,
    description: 'Reliable preventive home maintenance and small repairs handled in one scheduled visit.',
    address: 'Verdun 730',
    area: 'Verdun',
    phone: '+9611802808',
    whatsapp: '9613110108',
    latitude: 33.8794,
    longitude: 35.4865,
    openingHours: STANDARD_HOURS,
    avgRating: 4.6,
    reviewCount: 76,
  },
  {
    id: 'p9',
    name: 'CoolFix AC',
    categoryId: 9,
    description: 'AC servicing, gas refills, leak detection, cleaning, installation, and urgent summer repairs.',
    address: 'Furn El Chebbak main road',
    area: 'Furn El Chebbak',
    phone: '+9611292909',
    whatsapp: '9613110109',
    latitude: 33.8694,
    longitude: 35.5218,
    openingHours: { ...STANDARD_HOURS, sun: '10:00–15:00' },
    avgRating: 4.8,
    reviewCount: 134,
  },
  {
    id: 'p10',
    name: 'Appliance Doctor',
    categoryId: 10,
    description: 'Diagnosis and repair for washing machines, refrigerators, ovens, dryers, and dishwashers.',
    address: 'Bourj Hammoud main road',
    area: 'Bourj Hammoud',
    phone: '+9611263010',
    whatsapp: '9613110110',
    latitude: 33.8938,
    longitude: 35.5439,
    openingHours: STANDARD_HOURS,
    avgRating: 4.5,
    reviewCount: 64,
  },
  {
    id: 'p11',
    name: 'Cedar Woodworks',
    categoryId: 11,
    description: 'Custom shelves, door and cabinet repairs, furniture restoration, and precise on-site carpentry.',
    address: 'Armenia Street',
    area: 'Mar Mikhael',
    phone: '+9611443111',
    whatsapp: '9613110111',
    latitude: 33.8972,
    longitude: 35.5244,
    openingHours: STANDARD_HOURS,
    avgRating: 4.7,
    reviewCount: 52,
  },
  {
    id: 'p12',
    name: 'FreshCoat Painters',
    categoryId: 12,
    description: 'Interior and exterior painting with surface preparation, tidy work, and upfront estimates.',
    address: 'Badaro Street',
    area: 'Badaro',
    phone: '+9611393212',
    whatsapp: '9613110112',
    latitude: 33.8759,
    longitude: 35.5162,
    openingHours: STANDARD_HOURS,
    avgRating: 4.6,
    reviewCount: 47,
  },
  {
    id: 'p13',
    name: 'KeyNow Locksmith',
    categoryId: 13,
    description: 'Urgent lockouts, lock replacement, door alignment, and key duplication at your location.',
    address: 'Mobile service from Ras Beirut',
    area: 'Ras Beirut',
    phone: '+9613993313',
    whatsapp: '9613110113',
    latitude: 33.8998,
    longitude: 35.4785,
    openingHours: ALWAYS_OPEN,
    avgRating: 4.9,
    reviewCount: 155,
  },
  {
    id: 'p14',
    name: 'ClearHome Pest Control',
    categoryId: 14,
    description: 'Targeted treatment for ants, roaches, rodents, and bed bugs using home-safe methods.',
    address: 'Corniche El Mazraa',
    area: 'Mazraa',
    phone: '+9611663414',
    whatsapp: '9613110114',
    latitude: 33.8772,
    longitude: 35.4992,
    openingHours: STANDARD_HOURS,
    avgRating: 4.7,
    reviewCount: 88,
  },
  {
    id: 'p15',
    name: 'MoveWise Beirut',
    categoryId: 15,
    description: 'Apartment and office moves with packing, furniture protection, loading, and assembly.',
    address: 'Jnah service road',
    area: 'Jnah',
    phone: '+9611843515',
    whatsapp: '9613110115',
    latitude: 33.8599,
    longitude: 35.4863,
    openingHours: STANDARD_HOURS,
    avgRating: 4.8,
    reviewCount: 72,
  },
  {
    id: 'p16',
    name: 'WashWheels Mobile',
    categoryId: 16,
    description: 'Water-conscious mobile car wash and interior cleaning at home, work, or your parking spot.',
    address: 'Mobile service across Beirut',
    area: 'Beirut',
    phone: '+9613993616',
    whatsapp: '9613110116',
    latitude: 33.8895,
    longitude: 35.501,
    openingHours: { ...STANDARD_HOURS, sun: '9:00–14:00' },
    avgRating: 4.6,
    reviewCount: 91,
  },
  {
    id: 'p17',
    name: 'OneCall Handyman',
    categoryId: 17,
    description: 'Curtain rods, shelves, TV mounting, furniture assembly, silicone work, and everyday fixes.',
    address: 'Mobile service from Cola',
    area: 'Cola',
    phone: '+9611703717',
    whatsapp: '9613110117',
    latitude: 33.8724,
    longitude: 35.4987,
    openingHours: STANDARD_HOURS,
    avgRating: 4.8,
    reviewCount: 116,
  },
  {
    id: 'p18',
    name: 'Mishwar Express',
    categoryId: 18,
    description: 'Documents, pharmacy pickups, grocery runs, and small deliveries with live WhatsApp updates.',
    address: 'Service across central Beirut',
    area: 'Central Beirut',
    phone: '+9613993818',
    whatsapp: '9613110118',
    latitude: 33.889,
    longitude: 35.504,
    openingHours: { ...STANDARD_HOURS, sun: '10:00–18:00' },
    avgRating: 4.7,
    reviewCount: 203,
  },
  {
    id: 'p19',
    name: 'TechRevive Lab',
    categoryId: 19,
    description: 'Same-day phone screens, batteries, laptop diagnostics, data recovery, and software repair.',
    address: 'Bliss Street, near AUB',
    area: 'Hamra',
    phone: '+9611353919',
    whatsapp: '9613110119',
    latitude: 33.9002,
    longitude: 35.4792,
    openingHours: STANDARD_HOURS,
    avgRating: 4.7,
    reviewCount: 149,
  },
  {
    id: 'p20',
    name: 'CleanFold Laundry',
    categoryId: 20,
    description: 'Wash and fold, dry cleaning, ironing, and scheduled pickup and delivery across nearby areas.',
    address: 'Gouraud Street',
    area: 'Gemmayzeh',
    phone: '+9611444020',
    whatsapp: '9613110120',
    latitude: 33.8954,
    longitude: 35.5152,
    openingHours: { ...STANDARD_HOURS, sun: '10:00–16:00' },
    avgRating: 4.5,
    reviewCount: 68,
  },
];

export const REVIEWS: Review[] = [
  { id: 'r1', providerId: 'p1', userId: null, userName: 'Maya K.', rating: 5, comment: 'Arrived quickly and stopped the leak without making a mess.', createdAt: '2026-06-20' },
  { id: 'r2', providerId: 'p2', userId: null, userName: 'Omar H.', rating: 5, comment: 'Found the electrical fault fast and explained the repair clearly.', createdAt: '2026-06-12' },
  { id: 'r3', providerId: 'p4', userId: null, userName: 'Karim B.', rating: 5, comment: 'Reached me on the highway in under thirty minutes.', createdAt: '2026-05-30' },
  { id: 'r4', providerId: 'p7', userId: null, userName: 'Rita F.', rating: 5, comment: 'Easy booking and the apartment felt brand new afterward.', createdAt: '2026-06-25' },
  { id: 'r5', providerId: 'p13', userId: null, userName: 'Jad M.', rating: 5, comment: 'Professional, careful, and very quick during a stressful lockout.', createdAt: '2026-07-01' },
  { id: 'r6', providerId: 'p19', userId: null, userName: 'Lina S.', rating: 4, comment: 'My laptop was ready the same day and the price was fair.', createdAt: '2026-06-18' },
];

export function getCategory(id: number): Category | undefined {
  return CATEGORIES.find((category) => category.id === id);
}

export function getProvider(id: string): Provider | undefined {
  return PROVIDERS.find((provider) => provider.id === id);
}

export function getReviewsFor(providerId: string): Review[] {
  return REVIEWS.filter((review) => review.providerId === providerId);
}
